name: rmc's site
title: rmc's site
url: https://ianskinner1982.github.io
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
feed:
  posts_limit: 20
  # Exclude  all files from `pages` in sitemap











